name: MagmaMoney
version: 1.0
author: Wolf_IV
main: com.Wolf_IV.MagmaMoney.MainM
commands:
  shop:
    description: Create Shop
  recup:
    description: Recup Magma
  mgive:
    description: Gives money
    permission: mgive.use